[tool.poetry]
name = "pkg_example"
version = "0.1.0"
description = ""
authors = ["re76 <rernst76@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
